## Preprocessing

In [4]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import keras_tuner as kt

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [5]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN','NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [6]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [7]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_counts[application_counts<10].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
Other       11
Name: count, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
class_val = application_df['CLASSIFICATION'].value_counts()
class_val

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_val_1 = application_df['CLASSIFICATION'].value_counts().loc[lambda x: x>1]
class_val_1

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_val[class_val<100].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
app_dummies = pd.get_dummies(application_df)
app_dummies

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T3,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,False,False,False,True,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,False,False,False,True,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,False,False,False,True,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,False,False,False,True,...,False,False,False,False,True,False,False,False,True,False

In [13]:
# Split our preprocessed data into our features and target arrays
X = app_dummies.drop("IS_SUCCESSFUL", axis = 1).values
y = app_dummies['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_test, X_train, y_test, y_train = train_test_split(X, y, random_state=78)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [15]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = len(X_train[0])
hidden_layer1 = 8
hidden_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(input_dim=input_features, units=hidden_layer1,activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 432

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 483 (1.89 KB)
Trainable params: 483 (1.89 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [16]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [17]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
268/268 [==============================] - 2s 2ms/step - loss: 0.6393 - accuracy: 0.6343
Epoch 2/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5970 - accuracy: 0.6688
Epoch 3/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5803 - accuracy: 0.7064
Epoch 4/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5699 - accuracy: 0.7190
Epoch 5/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5616 - accuracy: 0.7187
Epoch 6/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5573 - accuracy: 0.7199
Epoch 7/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5545 - accuracy: 0.7212
Epoch 8/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5531 - accuracy: 0.7203
Epoch 9/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5523 - accuracy: 0.7223
Epoch 10/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5517 - accuracy: 0.7228
Epoch 11/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5510 - accuracy: 0.7233
Epoch 12/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5504 - accuracy: 0.7235
Epoch 13/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5497 - accuracy: 0.7209
Epoch 14/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5500 - accuracy: 0.7240
Epoch 15/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5493 - accuracy: 0.7231
Epoch 16/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5489 - accuracy: 0.7240
Epoch 17/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5485 - accuracy: 0.7238
Epoch 18/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7240
Epoch 19/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7234
Epoch 20/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7243
Epoch 21/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5470 - accuracy: 0.7236
Epoch 22/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5468 - accuracy: 0.7237
Epoch 23/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7238
Epoch 24/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7235
Epoch 25/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7235
Epoch 26/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5456 - accuracy: 0.7238
Epoch 27/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5453 - accuracy: 0.7252
Epoch 28/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5457 - accuracy: 0.7236
Epoch 29/100
268/268 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7256
Epoch 30/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5452 - accuracy: 0.7249
Epoch 31/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7249
Epoch 32/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7242
Epoch 33/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7247
Epoch 34/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7249
Epoch 35/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7240
Epoch 36/100
268/268 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7245
Epoch 37/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7247
Epoch 38/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5439 - accuracy: 0.7259
Epoch 39/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5440 - accuracy: 0.7254
Epoch 40/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7231
Epoch 41/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7251
Epoch 42/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7257
Epoch 43/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5433 - accuracy: 0.7251
Epoch 44/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7248
Epoch 45/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5431 - accuracy: 0.7263
Epoch 46/100
268/268 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7250
Epoch 47/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5429 - accuracy: 0.7251
Epoch 48/100
268/268 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7248
Epoch 49/100
268/268 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7261
Epoch 50/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5426 - accuracy: 0.7252
Epoch 51/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7255
Epoch 52/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7266
Epoch 53/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7259
Epoch 54/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7268
Epoch 55/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7259
Epoch 56/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7266
Epoch 57/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7243
Epoch 58/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7270
Epoch 59/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7264
Epoch 60/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7261
Epoch 61/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7265
Epoch 62/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7255
Epoch 63/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7261
Epoch 64/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7266
Epoch 65/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7247
Epoch 66/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7254
Epoch 67/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5412 - accuracy: 0.7264
Epoch 68/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5410 - accuracy: 0.7251
Epoch 69/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5410 - accuracy: 0.7250
Epoch 70/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5411 - accuracy: 0.7255
Epoch 71/100
268/268 [==============================] - 1s 4ms/step - loss: 0.5412 - accuracy: 0.7261
Epoch 72/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5407 - accuracy: 0.7268
Epoch 73/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7256
Epoch 74/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7272
Epoch 75/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7268
Epoch 76/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7266
Epoch 77/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5406 - accuracy: 0.7265
Epoch 78/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7262
Epoch 79/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7257
Epoch 80/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5406 - accuracy: 0.7277
Epoch 81/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7259
Epoch 82/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5401 - accuracy: 0.7270
Epoch 83/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7265
Epoch 84/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7275
Epoch 85/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7272
Epoch 86/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7256
Epoch 87/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7268
Epoch 88/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5401 - accuracy: 0.7263
Epoch 89/100
268/268 [==============================] - 1s 3ms/step - loss: 0.5398 - accuracy: 0.7270
Epoch 90/100
268/268 [==============================] - 1s 4ms/step - loss: 0.5397 - accuracy: 0.7261
Epoch 91/100
268/268 [==============================] - 1s 4ms/step - loss: 0.5395 - accuracy: 0.7265
Epoch 92/100
268/268 [==============================] - 1s 4ms/step - loss: 0.5399 - accuracy: 0.7283
Epoch 93/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7279
Epoch 94/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7268
Epoch 95/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7280
Epoch 96/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7266
Epoch 97/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7282
Epoch 98/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7256
Epoch 99/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7269
Epoch 100/100
268/268 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7262

In [18]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

804/804 - 1s - loss: 0.5606 - accuracy: 0.7160 - 1s/epoch - 2ms/step
Loss: 0.5606375932693481, Accuracy: 0.7160239219665527

In [19]:
# Export our model to HDF5 file
from google.colab import files

nn.save('AlphabetSoupCharity.h5')
files.download('AlphabetSoupCharity.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(